import { Item } from "./type";

export const terrazzoItems: Item[] = [
  {
    group: "VI",
    groupName: "Terrazzo",
    id: 1,
    img: "/engineered-terrazzo/group-VI/COLOSSEO.png",
    label: "COLOSSEO",
  },
  {
    group: "VI",
    groupName: "Terrazzo",
    id: 2,
    img: "/engineered-terrazzo/group-VI/RIVA.png",
    label: "RIVA",
  },
  {
    group: "VI",
    groupName: "Terrazzo",
    id: 3,
    img: "/engineered-terrazzo/group-VI/CEPPO.png",
    label: "CEPPO",
  },
  {
    group: "VI",
    groupName: "Terrazzo",
    id: 4,
    img: "/engineered-terrazzo/group-VI/ELBA.png",
    label: "ELBA",
  },
  {
    group: "VI",
    groupName: "Terrazzo",
    id: 5,
    img: "/engineered-terrazzo/group-VI/PLAZZO_WHITE.png",
    label: "PLAZZO WHITE",
  },
  {
    group: "VI",
    groupName: "Terrazzo",
    id: 6,
    img: "/engineered-terrazzo/group-VI/FORUM.png",
    label: "FORUM",
  },
  {
    group: "VI",
    groupName: "Terrazzo",
    id: 7,
    img: "/engineered-terrazzo/group-VI/PLAZZO_BLACK.png",
    label: "PLAZZO BLACK",
  },
  {
    group: "VI",
    groupName: "Terrazzo",
    id: 8,
    img: "/engineered-terrazzo/group-VI/IMPERIALE.png",
    label: "IMPERIALE",
  },
  {
    group: "VI",
    groupName: "Terrazzo",
    id: 9,
    img: "/engineered-terrazzo/group-VI/NAVONA.png",
    label: "NAVONA",
  },

  {
    group: "VII",
    groupName: "Terrazzo",
    id: 1,
    img: "/engineered-terrazzo/group-VII/HUDSON_SKY.png",
    label: "HUDSON SKY",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 2,
    img: "/engineered-terrazzo/group-VII/MAX_BOTTICINO.png",
    label: "MAX BOTTICINO",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 3,
    img: "/engineered-terrazzo/group-VII/MURANO.png",
    label: "MURANO",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 4,
    img: "/engineered-terrazzo/group-VII/SIENNA.png",
    label: "SIENNA",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 5,
    img: "/engineered-terrazzo/group-VII/DOCKS_GREY.png",
    label: "DOCKS GREY",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 6,
    img: "/engineered-terrazzo/group-VII/AMARA_LIGHT.png",
    label: "AMARA LIGHT",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 7,
    img: "/engineered-terrazzo/group-VII/TRENDY_GREY.png",
    label: "TRENDY GREY",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 8,
    img: "/engineered-terrazzo/group-VII/TERRA_GREY.png",
    label: "TERRA GREY",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 9,
    img: "/engineered-terrazzo/group-VII/URBAN_WHITE.png",
    label: "URBAN WHITE",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 10,
    img: "/engineered-terrazzo/group-VII/NEW_WHITE_DOVE_PRM.png",
    label: "NEW WHITE DOVE PRM",
  },
  {
    group: "VII",
    groupName: "Terrazzo",
    id: 11,
    img: "/engineered-terrazzo/group-VII/GRETA_GREY.png",
    label: "GRETA GREY",
  },

  {
    group: "VIII",
    groupName: "Terrazzo",
    id: 1,
    img: "/engineered-terrazzo/group-VIII/NEW_DELUXE_WHITE.png",
    label: "NEW DELUXE WHITE",
  },
  {
    group: "VIII",
    groupName: "Terrazzo",
    id: 2,
    img: "/engineered-terrazzo/group-VIII/SAVVANNA.png",
    label: "SAVVANNA",
  },
  {
    group: "VIII",
    groupName: "Terrazzo",
    id: 3,
    img: "/engineered-terrazzo/group-VIII/EXOTIC_GREEN.png",
    label: "EXOTIC GREEN",
  },
  {
    group: "VIII",
    groupName: "Terrazzo",
    id: 4,
    img: "/engineered-terrazzo/group-VIII/ELIO.png",
    label: "ELIO",
  },
  {
    group: "VIII",
    groupName: "Terrazzo",
    id: 5,
    img: "/engineered-terrazzo/group-VIII/SUPREME_BROWN.png",
    label: "SUPREME BROWN",
  },
  {
    group: "VIII",
    groupName: "Terrazzo",
    id: 6,
    img: "/engineered-terrazzo/group-VIII/JADE.png",
    label: "JADE",
  },
  {
    group: "VIII",
    groupName: "Terrazzo",
    id: 7,
    img: "/engineered-terrazzo/group-VIII/VINTAGE_SPRING.png",
    label: "VINTAGE SPRING",
  },
  {
    group: "VIII",
    groupName: "Terrazzo",
    id: 8,
    img: "/engineered-terrazzo/group-VIII/MATEO_WHITE.png",
    label: "MATEO WHITE",
  },
  {
    group: "IX",
    groupName: "Terrazzo",
    id: 1,
    img: "/engineered-terrazzo/group-IX/TERRA_CREAM.png",
    label: "TERRA CREAM",
  },
  {
    group: "IX",
    groupName: "Terrazzo",
    id: 2,
    img: "/engineered-terrazzo/group-IX/BLUE_TERRAZZO.png",
    label: "BLUE TERRAZZO",
  },
];

export const quartzItems: Item[] = [
  {
    group: "I",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-i/FOSTER_BIANCO.png",
    label: "FOSTER BIANCO",
  },
  {
    group: "I",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-i/FOSTER_GOLD.png",
    label: "FOSTER GOLD",
  },
  {
    group: "I-A",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-i-A/BIANCO_CRISTALLO.png",
    label: "BIANCO CRISTALLO",
  },
  {
    group: "I-A",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-i-A/BIANCO_NEVE.png",
    label: "BIANCO NEVE",
  },
  {
    group: "I-A",
    groupName: "Quartz",
    id: 3,
    img: "/engineered-quartz/group-i-A/CREMA_SCURO.png",
    label: "CREMA SCURO",
  },

  {
    group: "II",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-ii/BEIGE_DIAMANTE.png",
    label: "BEIGE DIAMANTE",
  },
  {
    group: "II",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-ii/MOCCA_DIAMANTE.png",
    label: "MOCCA DIAMANTE",
  },
  {
    group: "II",
    groupName: "Quartz",
    id: 3,
    img: "/engineered-quartz/group-ii/BEIGE_TUSCANY.png",
    label: "BEIGE TUSCANY",
  },
  {
    group: "II",
    groupName: "Quartz",
    id: 4,
    img: "/engineered-quartz/group-ii/CREMA_VERONA.png",
    label: "CREMA VERONA",
  },

  {
    group: "II",
    groupName: "Quartz",
    id: 5,
    img: "/engineered-quartz/group-ii/SANDY_DIAMANTE.png",
    label: "SANDY DIAMANTE",
  },
  {
    group: "II",
    groupName: "Quartz",
    id: 6,
    img: "/engineered-quartz/group-ii/DESERT_BROWN.png",
    label: "DESERT BROWN",
  },
  {
    group: "II",
    groupName: "Quartz",
    id: 7,
    img: "/engineered-quartz/group-ii/CEMENT.png",
    label: "CEMENT",
  },
  {
    group: "II",
    groupName: "Quartz",
    id: 8,
    img: "/engineered-quartz/group-ii/GRIGIO_DIAMANTE.png",
    label: "GRIGIO DIAMANTE",
  },
  {
    group: "II",
    groupName: "Quartz",
    id: 9,
    img: "/engineered-quartz/group-ii/BIANCO_DIAMANTE.png",
    label: "BIANCO DIAMANTE",
  },
  {
    group: "II",
    groupName: "Quartz",
    id: 10,
    img: "/engineered-quartz/group-ii/JERUSALEM_DIAMANTE.png",
    label: "JERUSALEM DIAMANTE",
  },
  {
    group: "II",
    groupName: "Quartz",
    id: 11,
    img: "/engineered-quartz/group-ii/NERO_DIAMANTE.png",
    label: "NERO DIAMANTE",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-iii/ASH_GREY.png",
    label: "ASH GREY",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-iii/GRIGIO_LONDRA.png",
    label: "GRIGIO LONDRA",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 3,
    img: "/engineered-quartz/group-iii/COSMOPOLITIAN.png",
    label: "COSMOPOLITIAN",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 4,
    img: "/engineered-quartz/group-iii/PEPPERCORN_WHITE.png",
    label: "PEPPERCORN WHITE",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 5,
    img: "/engineered-quartz/group-iii/BIANCO_CLASSIC.png",
    label: "BIANCO CLASSIC",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 6,
    img: "/engineered-quartz/group-iii/METROPOLITAN.png",
    label: "METROPOLITAN",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 7,
    img: "/engineered-quartz/group-iii/PEARL_GREY.png",
    label: "PEARL GREY",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 8,
    img: "/engineered-quartz/group-iii/VETRO_BIANCO.png",
    label: "VETRO BIANCO",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 9,
    img: "/engineered-quartz/group-iii/NERO_CLASSIC.png",
    label: "NERO CLASSIC",
  },
  {
    group: "III",
    groupName: "Quartz",
    id: 10,
    img: "/engineered-quartz/group-iii/TORRES.png",
    label: "TORRES",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-v/CALACATTA_PRISTINE.png",
    label: "CALACATTA PRISTINE",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-v/CALACATTA_VENEZIA.png",
    label: "CALACATTA VENEZIA",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 3,
    img: "/engineered-quartz/group-v/CALACATTA_RIVOLO.png",
    label: "CALACATTA RIVOLO",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 4,
    img: "/engineered-quartz/group-v/CARARA_DUO.png",
    label: "CARARA DUO",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 5,
    img: "/engineered-quartz/group-v/CLASSIC_PEARL.png",
    label: "CLASSIC PEARL",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 6,
    img: "/engineered-quartz/group-v/CARARA_LUMAS.png",
    label: "CARARA LUMAS",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 7,
    img: "/engineered-quartz/group-v/BERMINGHAM.png",
    label: "BERMINGHAM",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 8,
    img: "/engineered-quartz/group-v/NEW_EXTRA_WHITE.png",
    label: "NEW EXTRA WHITE",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 9,
    img: "/engineered-quartz/group-v/CREMA_GOLD.png",
    label: "CREMA GOLD",
  },
  {
    group: "V",
    groupName: "Quartz",
    id: 10,
    img: "/engineered-quartz/group-v/NISLEY.png",
    label: "NISLEY",
  },

  {
    group: "VI",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-vi/WIZZARD.png",
    label: "WIZZARD",
  },
  {
    group: "VI",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-vi/CALACATTA_NERO.png",
    label: "CALACATTA NERO",
  },
  {
    group: "VI",
    groupName: "Quartz",
    id: 3,
    img: "/engineered-quartz/group-vi/TUNDRA.png",
    label: "TUNDRA",
  },
  {
    group: "VI",
    groupName: "Quartz",
    id: 4,
    img: "/engineered-quartz/group-vi/FLORIDA_GOLD.png",
    label: "FLORIDA GOLD",
  },
  {
    group: "VI",
    groupName: "Quartz",
    id: 5,
    img: "/engineered-quartz/group-vi/NEW_FOSSIL_GREY.png",
    label: "NEW FOSSIL GREY",
  },
  {
    group: "VI",
    groupName: "Quartz",
    id: 6,
    img: "/engineered-quartz/group-vi/ROCOCO.png",
    label: "ROCOCO",
  },
  {
    group: "VI",
    groupName: "Quartz",
    id: 7,
    img: "/engineered-quartz/group-vi/MARAZIO_DUO.png",
    label: "MARAZIO DUO",
  },
  {
    group: "VI",
    groupName: "Quartz",
    id: 8,
    img: "/engineered-quartz/group-vi/MINUTE_WHITE.png",
    label: "MINUTE WHITE",
  },
  {
    group: "VII",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-vii/ALLURING.png",
    label: "ALLURING",
  },
  {
    group: "VII",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-vii/CALACATTA_LAZZA.png",
    label: "CALACATTA LAZZA",
  },
  {
    group: "VII",
    groupName: "Quartz",
    id: 3,
    img: "/engineered-quartz/group-vii/BIANCO_VENATINO.png",
    label: "BIANCO VENATINO",
  },
  {
    group: "VII",
    groupName: "Quartz",
    id: 4,
    img: "/engineered-quartz/group-vii/CRYSTAL_BLISS.png",
    label: "CRYSTAL BLISS",
  },
  {
    group: "VII",
    groupName: "Quartz",
    id: 5,
    img: "/engineered-quartz/group-vii/CALACATTA_IMPERAILE.png",
    label: "CALACATTA IMPERAILE",
  },
  {
    group: "VII",
    groupName: "Quartz",
    id: 6,
    img: "/engineered-quartz/group-vii/CRYSTAL_SERENE.png",
    label: "CRYSTAL SERENE",
  },
  {
    group: "VII",
    groupName: "Quartz",
    id: 7,
    img: "/engineered-quartz/group-vii/AQUA_WAVE.png",
    label: "AQUA WAVE",
  },
  {
    group: "VIII",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-viii/CALACATTA_DUO.png",
    label: "CALACATTA DUO",
  },
  {
    group: "VIII",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-viii/HIMALAYA.png",
    label: "HIMALAYA",
  },
  {
    group: "IX",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-ix/BLUE_CRYSTAL_AGATHE.png",
    label: "BLUE CRYSTAL AGATHE",
  },
  {
    group: "IX",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-ix/GRAND_ANTIQUE.png",
    label: "GRAND ANTIQUE",
  },
  {
    group: "IX",
    groupName: "Quartz",
    id: 3,
    img: "/engineered-quartz/group-ix/VOILA.png",
    label: "VOILA",
  },
  {
    group: "X",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-x/MICHEAL_ANGELO.png",
    label: "MICHEAL ANGELO",
  },
  {
    group: "X",
    groupName: "Quartz",
    id: 2,
    img: "/engineered-quartz/group-x/BIANCO_CINIATI.png",
    label: "BIANCO CINIATI",
  },
  {
    group: "X",
    groupName: "Quartz",
    id: 3,
    img: "/engineered-quartz/group-x/PANDA_WHITE.png",
    label: "PANDA WHITE",
  },
  {
    group: "X",
    groupName: "Quartz",
    id: 4,
    img: "/engineered-quartz/group-x/VERDE_BOTANIK_CLASSICO.png",
    label: "VERDE BOTANIK CLASSICO",
  },
  {
    group: "XI",
    groupName: "Quartz",
    id: 1,
    img: "/engineered-quartz/group-xi/BIANCO_CRYSTAL.png",
    label: "BIANCO CRYSTAL",
  },
];

export const marbleItems: Item[] = [
  {
    group: "I",
    groupName: "Marble",
    id: 1,
    img: "/engineered-marble/group-i/CANDY_WHITE.png",
    label: "CANDY WHITE",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 1,
    img: "/engineered-marble/group-ii/ARTIC_WHITE.png",
    label: "ARTIC WHITE",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 2,
    img: "/engineered-marble/group-ii/DALLIA.png",
    label: "DALLIA",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 3,
    img: "/engineered-marble/group-ii/ROMOLO.png",
    label: "ROMOLO",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 4,
    img: "/engineered-marble/group-ii/BIANCO_VENUS.png",
    label: "BIANCO VENUS",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 5,
    img: "/engineered-marble/group-ii/CLASSIC_CRYSTAL.png",
    label: "CLASSIC CRYSTAL",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 6,
    img: "/engineered-marble/group-ii/OTTONE.png",
    label: "OTTONE",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 7,
    img: "/engineered-marble/group-ii/CREMA_NOVA.png",
    label: "CREMA NOVA",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 8,
    img: "/engineered-marble/group-ii/RAFFAELE.png",
    label: "RAFFAELE",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 9,
    img: "/engineered-marble/group-ii/CRISTALLO.png",
    label: "CRISTALLO",
  },
  {
    group: "II",
    groupName: "Marble",
    id: 10,
    img: "/engineered-marble/group-ii/ROMEO.png",
    label: "ROMEO",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 1,
    img: "/engineered-marble/group-iii/ARCADIO.png",
    label: "ARCADIO",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 2,
    img: "/engineered-marble/group-iii/GRIGIO_CLASSICO.png",
    label: "GRIGIO CLASSICO",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 3,
    img: "/engineered-marble/group-iii/VALENTE.png",
    label: "VALENTE",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 4,
    img: "/engineered-marble/group-iii/AURELIO_NUOVO.png",
    label: "AURELIO NUOVO",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 5,
    img: "/engineered-marble/group-iii/LUNA.png",
    label: "LUNA",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 6,
    img: "/engineered-marble/group-iii/OTTOMAN_BEIGE.png",
    label: "OTTOMAN BEIGE",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 7,
    img: "/engineered-marble/group-iii/CLEOPATRA.png",
    label: "CLEOPATRA",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 8,
    img: "/engineered-marble/group-iii/MINTA_FLURRY.png",
    label: "MINTA FLURRY",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 9,
    img: "/engineered-marble/group-iii/GARDENIA.png",
    label: "GARDENIA",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 10,
    img: "/engineered-marble/group-iii/PALLADIO_GREY.png",
    label: "PALLADIO GREY",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 11,
    img: "/engineered-marble/group-iii/GRIGIO_BILLIAME.png",
    label: "GRIGIO BILLIAME",
  },
  {
    group: "III",
    groupName: "Marble",
    id: 12,
    img: "/engineered-marble/group-iii/TIBERIO.png",
    label: "TIBERIO",
  },

  {
    group: "IV",
    groupName: "Marble",
    id: 1,
    img: "/engineered-marble/group-iv/ALTHEA.png",
    label: "ALTHEA",
  },
  {
    group: "IV",
    groupName: "Marble",
    id: 2,
    img: "/engineered-marble/group-iv/ALYSSA.png",
    label: "ALYSSA",
  },
  {
    group: "IV",
    groupName: "Marble",
    id: 3,
    img: "/engineered-marble/group-iv/BALTIC_GREY.png",
    label: "BALTIC GREY",
  },
  {
    group: "IV",
    groupName: "Marble",
    id: 4,
    img: "/engineered-marble/group-iv/CAMELIA.png",
    label: "CAMELIA",
  },
  {
    group: "IV",
    groupName: "Marble",
    id: 5,
    img: "/engineered-marble/group-iv/DANTEA.png",
    label: "DANTEA",
  },
  {
    group: "IV",
    groupName: "Marble",
    id: 6,
    img: "/engineered-marble/group-iv/EMPERADOR_CHIARA.png",
    label: "EMPERADOR CHIARA",
  },
  {
    group: "IV",
    groupName: "Marble",
    id: 7,
    img: "/engineered-marble/group-iv/EMPERADOR_SCURO.png",
    label: "EMPERADOR SCURO",
  },
  {
    group: "IV",
    groupName: "Marble",
    id: 8,
    img: "/engineered-marble/group-iv/FRESH_CONCRETE.png",
    label: "FRESH CONCRETE",
  },
  {
    group: "IV",
    groupName: "Marble",
    id: 9,
    img: "/engineered-marble/group-iv/MAJESTIC_GREY.png",
    label: "MAJESTIC GREY",
  },
  {
    group: "IV",
    groupName: "Marble",
    id: 10,
    img: "/engineered-marble/group-iv/SLEEK_CONCRETE.png",
    label: "SLEEK CONCRETE",
  },
  {
    group: "V-A",
    groupName: "Marble",
    id: 1,
    img: "/engineered-marble/group-v-a/AMELIA.png",
    label: "AMELIA",
  },
  {
    group: "V-B",
    groupName: "Marble",
    id: 1,
    img: "/engineered-marble/group-v-b/BIANCO_THASOS.png",
    label: "BINCO THASOS",
  },
];
